#!/bin/bash
# THIS FILE IS GENERATED BY tools/setup_python.sh
export PYTHONUSERBASE="/workspace/Muskits/tools/python_user_base"
export PATH="/workspace/Muskits/tools/python_user_base/bin":${PATH}
export PATH=/opt/conda/bin:${PATH}
